# Generated by Django 4.0.5 on 2022-06-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouse_name', models.CharField(max_length=50)),
                ('experimental_model', models.CharField(max_length=50)),
                ('heredity', models.CharField(max_length=50, null=True)),
                ('genotype', models.CharField(max_length=50, null=True)),
                ('uploadedFile', models.FileField(upload_to='Uploaded Files/')),
            ],
        ),
    ]
